name: Deploy to S3 and Invalidate CloudFront

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run test(s)
              run: |
                  if ! grep -iq "Guillermo" dist/index.html; then
                    echo "Your first name is not in the index.html file. Please add it and try again."
                    exit 1
                  fi

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              with:
                  source_dir: "dist"

            - name: Invalidate CloudFront Cache
              if: secrets.CLOUDFRONT_DISTRIBUTION_ID != ''
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
